### ISSUE TITLE
20바이트 데이터의 encryption값이 다릅니다.

### ISSUE THREAD

**Issue by xiote** [zajann/seed#1]
-- 아래는 zajann/seed 결과입니다. ---
PlanText: 12341234123412341234
Encrypted: [242 191 226 101 41 79 67 13 80 81 197 44 168 204 185 207 242 77 227 38 239 138 238 66 90 3 226 204 247 125 208 19]
Decrypted: 12341234123412341234

Key 	: 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76
Plaintext 	: 31 32 33 34 31 32 33 34 31 32 33 34 31 32 33 34 31 32 33 34
Ciphertext(SEED_ECB_Encrypt) 	: **f2 bf e2 65 29 4f 43 0d 50 51 c5 2c a8 cc b9 cf f2 4d e3 26 ef 8a ee 42 5a 03 e2 cc f7 7d d0 13**

-- 아래는 KISA 자바소스 결과입니다. ---
[ Test SEED reference code ECB ]

Key		: 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 
Plaintext	: 31 32 33 34 31 32 33 34 31 32 33 34 31 32 33 34 31 32 33 34 

Ciphertext(SEED_ECB_Encrypt)	: **f2 bf e2 65 29 4f 43 d 50 51 c5 2c a8 cc b9 cf 76 cd 43 aa 9e 1a 5 cf 32 88 6a ca a7 5 c7 ce** 
Plaintext(SEED_ECB_Decrypt)	: 31 32 33 34 31 32 33 34 31 32 33 34 31 32 33 34 

-- 아래는 go코드 입니다. ---

```golang
package main

import ( 
        "fmt"

        "github.com/zajann/seed"
)

func main() { 
        // You can use key to string, lenght SHOULD be 16
        key := "vvvvvvvvvvvvvvvv"

        // Init seed with key
        if err := seed.InitECB(key); err != nil { 
                panic(err)
        } 

        plainText := "12341234123412341234"

        // Encrypte
        encrypted, err := seed.ECBEncryptAll([]byte(plainText))
        if err != nil { 
                panic(err)
        } 

        // Decrypte
        decrypted, err := seed.ECBDecryptAll(encrypted)
        if err != nil { 
                panic(err)
        } 

        fmt.Printf("PlanText: %s\n", plainText)
        fmt.Printf("Encrypted: %v\n", encrypted)
        fmt.Printf("Decrypted: %s\n", string(decrypted))
        fmt.Println()
        fmt.Printf("Key \t: % x\n", key)
        fmt.Printf("Plaintext \t: % x\n", plainText)
        fmt.Printf("Ciphertext(SEED_ECB_Encrypt) \t: % x\n", encrypted)
}  
```

**Comment by xiote-dev** [comment]
더 확인하고 다시 이슈등록하겠습니다.
